language: php

before_script:
    - composer self-update
    - composer install --prefer-source
    - pear config-set auto_discover 1
    - pear install PHP_CodeSniffer

script:
    - phpunit
    - phpcs src --standard PSR1
    - phpcs src --standard PSR2

env:
  - DB=mysql

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm